/**
 * ML-DSA-65 cross-language compatibility tests.
 *
 * Verifies that @noble/post-quantum and the fips204 Rust crate produce
 * byte-identical outputs when given the same deterministic inputs,
 * confirming full FIPS 204 compliance and shell-chain interoperability.
 *
 * Fixture: tests/fixtures/mldsa65-cross-lang.json
 * (Generated by: cargo run -p shell-crypto --bin gen_mldsa_vectors)
 */

import assert from 'node:assert/strict';
import test from 'node:test';

import { ml_dsa65 } from '@noble/post-quantum/ml-dsa.js';

import { MlDsa65Adapter } from '../dist/adapters.js';
import { derivePqAddressFromPublicKey } from '../dist/address.js';
import { SIGNATURE_TYPE_IDS } from '../dist/signer.js';

import fixture from './fixtures/mldsa65-cross-lang.json' with { type: 'json' };

// ── Helpers ──────────────────────────────────────────────────────────────────

function hexToBytes(hex) {
  const clean = hex.replace(/^0x/, '');
  const bytes = new Uint8Array(clean.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

function bytesToHex(bytes) {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

// Pre-decoded fixture data (shared across tests)
const keygen_seed  = hexToBytes(fixture.keygen_seed_hex);
const pk_bytes     = hexToBytes(fixture.public_key_hex);
const sk_bytes     = hexToBytes(fixture.secret_key_hex);
const message      = hexToBytes(fixture.message_hex);
const rust_sig     = hexToBytes(fixture.rust_vector.signature_hex);
const noble_sig    = hexToBytes(fixture.noble_vector.signature_hex);

// ── Key generation ───────────────────────────────────────────────────────────

test('cross-lang: Noble keygen from seed matches Rust fixture pk/sk', () => {
  const key = ml_dsa65.keygen(keygen_seed);

  assert.equal(
    bytesToHex(key.publicKey),
    fixture.public_key_hex,
    'Noble public key must match Rust keygen_from_seed output',
  );
  assert.equal(
    bytesToHex(key.secretKey),
    fixture.secret_key_hex,
    'Noble secret key must match Rust keygen_from_seed output',
  );
  assert.equal(key.publicKey.length, fixture.key_sizes.public_key_len);
  assert.equal(key.secretKey.length, fixture.key_sizes.secret_key_len);
});

test('cross-lang: FIPS 204 key sizes match specification', () => {
  assert.equal(fixture.key_sizes.public_key_len, 1952, 'ML-DSA-65 pk = 1952 bytes');
  assert.equal(fixture.key_sizes.secret_key_len, 4032, 'ML-DSA-65 sk = 4032 bytes');
  assert.equal(fixture.key_sizes.signature_len, 3309, 'ML-DSA-65 sig = 3309 bytes');
});

// ── Deterministic signature production ────────────────────────────────────────

test('cross-lang: Noble deterministic sig matches Rust fixture sig', () => {
  // Noble: { extraEntropy: false } → rnd = [0;32]
  // Rust: try_sign_with_seed(&[0u8;32], ...) → same rnd
  const sig = ml_dsa65.sign(message, sk_bytes, { extraEntropy: false });

  assert.equal(sig.length, fixture.key_sizes.signature_len);
  assert.equal(
    bytesToHex(sig),
    fixture.rust_vector.signature_hex,
    'Noble sig (rnd=[0;32]) must be byte-identical to Rust sig (rnd=[0;32])',
  );
  assert.equal(
    bytesToHex(sig),
    fixture.noble_vector.signature_hex,
    'Noble sig must match committed noble_vector',
  );
  assert.equal(
    fixture.rust_vector.signature_hex,
    fixture.noble_vector.signature_hex,
    'Rust and Noble produce identical signatures for the same deterministic inputs',
  );
});

// ── Cross-language verification ────────────────────────────────────────────────

test('cross-lang: Noble verifies Rust-generated signature', () => {
  const ok = ml_dsa65.verify(rust_sig, message, pk_bytes);
  assert.equal(ok, true, 'Noble must verify Rust fips204-generated signature');
});

test('cross-lang: Noble verifies Noble-generated signature', () => {
  const ok = ml_dsa65.verify(noble_sig, message, pk_bytes);
  assert.equal(ok, true, 'Noble must verify its own committed signature');
});

test('cross-lang: wrong message fails verification', () => {
  const wrongMsg = new TextEncoder().encode('wrong message');
  const ok = ml_dsa65.verify(rust_sig, wrongMsg, pk_bytes);
  assert.equal(ok, false, 'verification must fail for wrong message');
});

test('cross-lang: wrong key fails verification', () => {
  const otherKey = ml_dsa65.keygen(new Uint8Array(32).fill(0x99));
  const ok = ml_dsa65.verify(rust_sig, message, otherKey.publicKey);
  assert.equal(ok, false, 'verification must fail for wrong public key');
});

// ── MlDsa65Adapter integration ────────────────────────────────────────────────

test('cross-lang: MlDsa65Adapter.fromKeyPair verifies Rust sig', async () => {
  const adapter = MlDsa65Adapter.fromKeyPair(pk_bytes, sk_bytes);

  // Verify rust_sig using Noble internals (adapter doesn't expose verify)
  const ok = ml_dsa65.verify(rust_sig, message, adapter.getPublicKey());
  assert.equal(ok, true, 'MlDsa65Adapter key must verify Rust-generated sig');
});

test('cross-lang: MlDsa65Adapter.fromKeyPair signs and Rust would verify', async () => {
  const adapter = MlDsa65Adapter.fromKeyPair(pk_bytes, sk_bytes);
  const sig = await adapter.sign(message);

  assert.equal(sig.length, 3309, 'adapter signature must be 3309 bytes');

  // Verify the new sig with Noble
  const ok = ml_dsa65.verify(sig, message, adapter.getPublicKey());
  assert.equal(ok, true, 'adapter-generated sig must be Noble-verifiable');
  // Note: adapter.sign() uses real randomness, so sig != fixture sig.
  // The corresponding Rust-side test (cross_lang.rs) verifies the committed sigs.
});

// ── Address derivation compatibility ─────────────────────────────────────────

test('cross-lang: address derivation is deterministic from fixture pk', () => {
  // ML-DSA-65 has algo_id = 1
  const algoId = SIGNATURE_TYPE_IDS['ML-DSA-65'];
  assert.equal(algoId, 1, 'ML-DSA-65 algo_id must be 1');

  const addr = derivePqAddressFromPublicKey(pk_bytes, algoId);
  assert.ok(addr.startsWith('pq1'), 'address must be pq1 bech32');

  // Same key → same address (deterministic)
  const addr2 = derivePqAddressFromPublicKey(pk_bytes, algoId);
  assert.equal(addr, addr2, 'address derivation must be deterministic');

  // Different algo_id → different address (algo separation)
  const addrDilithium = derivePqAddressFromPublicKey(pk_bytes, 0);
  assert.notEqual(
    addr,
    addrDilithium,
    'ML-DSA-65 (id=1) and Dilithium3 (id=0) must yield different addresses',
  );
});
