export {
  SHELL_ADDRESS_LENGTH,
  bytesToShellAddress,
  deriveShellAddressFromPublicKey,
  isShellAddress,
  normalizeShellAddress,
  shellAddressToBytes,
  // Legacy aliases (deprecated)
  bytesToPqAddress,
  derivePqAddressFromPublicKey,
  isPqAddress,
  normalizePqAddress,
  pqAddressVersion,
  pqAddressToBytes,
} from "./address.js";
export {
  createShellProvider,
  createShellPublicClient,
  createShellWsClient,
  ShellProvider,
  shellDevnet,
  type ShellChainConfig,
  type ShellPublicClient,
  type CreateShellPublicClientOptions,
} from "./provider.js";
export {
  accountManagerAddress,
  cancelRecoverySelector,
  clearValidationCodeSelector,
  encodeCancelRecoveryCalldata,
  encodeClearValidationCodeCalldata,
  encodeExecuteRecoveryCalldata,
  encodeRotateKeyCalldata,
  encodeSetGuardiansCalldata,
  encodeSetValidationCodeCalldata,
  encodeSubmitRecoveryCalldata,
  executeRecoverySelector,
  isSystemContractAddress,
  rotateKeySelector,
  setGuardiansSelector,
  setValidationCodeSelector,
  submitRecoverySelector,
  validatorRegistryAddress,
} from "./system-contracts.js";
export {
  AA_BUNDLE_TX_TYPE,
  AA_MAX_INNER_CALLS,
  buildBatchTransaction,
  buildClearValidationCodeTransaction,
  buildContractPaymasterTransaction,
  buildInnerCall,
  buildInnerTransfer,
  buildRotateKeyTransaction,
  buildSessionKeyTransaction,
  buildSetValidationCodeTransaction,
  buildSignature,
  buildSignedTransaction,
  buildSponsoredTransaction,
  buildSystemTransaction,
  buildTransaction,
  buildTransferTransaction,
  DEFAULT_AA_GAS_LIMIT,
  DEFAULT_MAX_FEE_PER_GAS,
  DEFAULT_MAX_PRIORITY_FEE_PER_GAS,
  DEFAULT_SYSTEM_GAS_LIMIT,
  DEFAULT_TRANSFER_GAS_LIMIT,
  DEFAULT_TX_TYPE,
  hashBatchTransaction,
  hashPaymasterTransaction,
  hashTransaction,
  type BuildBatchTransactionOptions,
  type BuildContractPaymasterTransactionOptions,
  type BuildSessionKeyTransactionOptions,
  type BuildSponsoredTransactionOptions,
} from "./transactions.js";
export {
  buildContractCallTransaction,
  buildDeployTransaction,
  decodeFunctionResult,
  deployContract,
  encodeFunctionData,
  readContract,
  waitForTransactionReceipt,
  writeContract,
  type BuildContractCallTransactionOptions,
  type BuildDeployTransactionOptions,
  type ContractReadOptions,
  type ContractWriteOptions,
  type ContractWriteResult,
  type DecodeContractFunctionResultOptions,
  type DeployContractOptions,
  type DeployContractResult,
  type EncodeContractFunctionDataOptions,
  type ShellContractArtifact,
  type WaitForTransactionReceiptOptions,
} from "./contracts.js";
export {
  assertSignerMatchesKeystore,
  decryptKeystore,
  exportEncryptedKeyJson,
  withDecryptedKeystoreSigner,
  parseEncryptedKey,
  validateEncryptedKeyAddress,
  type ParsedShellKeystore,
} from "./keystore.js";
export {
  adapterFromKeyPair,
  generateAdapter,
  generateMlDsa65KeyPair,
  generateSlhDsaKeyPair,
  MlDsa65Adapter,
  SlhDsaAdapter,
  type MlDsa65KeyPair,
  type SlhDsaKeyPair,
} from "./adapters.js";
export {
  buildShellSignature,
  publicKeyFromHex,
  ShellSigner,
  signatureTypeFromKeyType,
  type SignerAdapter,
} from "./signer.js";
export { AA_MAX_PAYMASTER_CONTEXT, AA_SESSION_KEY_GAS_SURCHARGE } from "./types.js";
export { formatShellRpcTxType } from "./types.js";
export type {
  AaBundle,
  AaInnerCall,
  AddressLike,
  GuardianConfig,
  HexString,
  RecoveryProposal,
  SessionAuth,
  ShellAccessListItem,
  ShellAddressSummary,
  ShellAddressSummaryOptions,
  ShellBatchInnerCallRequest,
  ShellBatchInnerGas,
  ShellBlocksRange,
  ShellBlocksRangeOptions,
  ShellCipherParams,
  ShellEncryptedKey,
  ShellEstimateBatchRequest,
  ShellEstimateBatchResult,
  ShellEstimatePaymasterGasRequest,
  ShellEstimatePaymasterGasResult,
  ShellKnownRpcTxType,
  ShellIsSponsoredResult,
  ShellKdfParams,
  ShellNodeInfo,
  ShellPaymasterPolicy,
  ShellPaymasterSimulationStatus,
  ShellReadableTxType,
  ShellRewardKind,
  ShellRpcBlock,
  ShellRpcCapabilities,
  ShellRpcListDirection,
  ShellRpcReceipt,
  ShellRpcTransaction,
  ShellRpcTransactionSummary,
  ShellRpcTxType,
  ShellRpcV2TxDetail,
  ShellDecodedProofInput,
  ShellSendTransactionParams,
  ShellSignature,
  ShellStorageProfile,
  ShellTransactionRequest,
  ShellTxByAddressPage,
  ShellTxByAddressV2Options,
  ShellTxByAddressV2Page,
  ShellTxWitness,
  ShellTransactionSummaryResult,
  ShellValidatorSnapshot,
  ShellValidatorSnapshotOptions,
  ShellProposerStats,
  ShellChainSnapshot,
  ShellWitnessBundle,
  ShellWitnessRootResult,
  SignedShellTransaction,
  SignatureTypeName,
} from "./types.js";
export {
  validateAddress,
  validateNonNegativeBigInt,
  validateNonNegativeInteger,
  validateRpcUrl,
} from "./validation.js";
export {
  ALGO_MLDSA65,
  ALGO_SLH_DSA,
  HD_COIN_TYPE,
  HD_PURPOSE,
  HARDENED_OFFSET,
  HD_SESSION_ACCOUNT,
  HD_SESSION_SUBTREE,
  MLDSA65_PK_LENGTH,
  SLHDSA_PK_LENGTH,
  accountToRecord,
  deriveAccount,
  deriveAtPath,
  deriveChildNode,
  deriveMlDsa65Account,
  deriveSlhDsaAccount,
  deriveSessionKey,
  formatPath,
  generateMnemonic,
  masterNodeFromSeed,
  mnemonicToSeed,
  parsePath,
  validateHdMnemonic,
  type HdAccount,
  type HdAccountRecord,
  type HdAlgo,
  type HdNode,
} from "./hdwallet.js";
export {
  PQTX_SESSION_DOMAIN,
  computeSessionAuthHash,
  createSessionAuth,
  finalizeSessionAuth,
  validateSessionAuthShape,
  type SessionKeyConfig,
} from "./session.js";
